CREATE TABLE CLIENTE(
	IDCLIENTE			UNIQUEIDENTIFIER	NOT NULL,
	NOME				NVARCHAR(150)		NOT NULL,
	CPF					NVARCHAR(11)		NOT NULL,
	TELEFONE			NVARCHAR(14)		NOT NULL,
	EMAIL				NVARCHAR(40)		NOT NULL,
	DATANASCIMENTO		DATE			NOT NULL,
	PRIMARY KEY(IDCLIENTE))
GO

CREATE PROCEDURE SP_INSERIR_CLIENTE
	@NOME				NVARCHAR(150),
	@CPF				NVARCHAR(11), 
	@TELEFONE			NVARCHAR(14),
	@EMAIL				NVARCHAR(40),
	@DATANASCIMENTO		DATE
AS
BEGIN
	BEGIN TRANSACTION
		INSERT INTO CLIENTE(
			IDCLIENTE,
			NOME,
			CPF,
			TELEFONE,
			EMAIL,
			DATANASCIMENTO)
		VALUES(
			NEWID(),
			@NOME,
			@CPF,
			@TELEFONE,
			@EMAIL,
			@DATANASCIMENTO)
	COMMIT
END
GO

CREATE PROCEDURE SP_ALTERAR_CLIENTE
    @IDCLIENTE			UNIQUEIDENTIFIER,
	@NOME				NVARCHAR(150),
	@CPF				NVARCHAR(11), 
	@TELEFONE			NVARCHAR(14),
	@EMAIL				NVARCHAR(40),
	@DATANASCIMENTO		DATE
AS
BEGIN
	BEGIN TRANSACTION
		UPDATE CLIENTE SET
			NOME = @NOME,
			CPF = @CPF,
			TELEFONE = @TELEFONE,
			EMAIL = @EMAIL,
			DATANASCIMENTO = @DATANASCIMENTO
		WHERE
			IDCLIENTE = @IDCLIENTE
	COMMIT
END
GO

CREATE PROCEDURE SP_EXCLUIR_CLIENTE
    @IDCLIENTE	UNIQUEIDENTIFIER	
AS
BEGIN
	BEGIN TRANSACTION
		DELETE FROM CLIENTE
		WHERE
			IDCLIENTE = @IDCLIENTE
	COMMIT
END
GO

CREATE PROCEDURE SP_CONSULTAR_CLIENTES
AS
BEGIN
	SELECT * FROM CLIENTE
	ORDER BY NOME ASC
END
GO

CREATE PROCEDURE SP_OBTER_CLIENTE
	@IDCLIENTE		UNIQUEIDENTIFIER
AS
BEGIN
	SELECT * FROM CLIENTE
	WHERE IDCLIENTE = @IDCLIENTE
END
GO